# Generated by Django 5.2.4 on 2025-07-31 11:49

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_report_bank_additions_report_hand_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=myapp1.fields.ChoiceIntegerField([(0, 'Electric Bill'), (1, 'Water Bill'), (2, "Priest's Stipend"), (3, 'Food'), (4, 'Transportation'), (5, 'Repairs/Maintenance'), (6, 'Worship'), (7, 'Evangelization'), (8, 'Service'), (9, 'Stewardship'), (10, 'Youth'), (11, 'Family & Life '), (12, 'Recollection/Seminar'), (13, 'Others')], 0),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=myapp1.fields.ChoiceIntegerField([(0, 'Mass Bag Collections'), (1, 'Mass Envelope Offerings'), (2, 'Mass Intentions'), (3, 'Donations'), (4, 'Solicitations')], 0),
        ),
    ]
