# Generated by Django 5.2.4 on 2025-07-31 11:50

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0013_expense_category_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=myapp1.fields.ChoiceIntegerField([(0, 'Electric Bill'), (1, 'Water Bill'), (2, "Priest's Stipend"), (3, 'Food'), (4, 'Transportation'), (5, 'Repairs/Maintenance'), (6, 'Worship'), (7, 'Evangelization'), (8, 'Service'), (9, 'Stewardship'), (10, 'Youth'), (11, 'Family & Life'), (12, 'Recollection/Seminar'), (13, 'Others')], 0),
        ),
    ]
