# Generated by Django 5.2.4 on 2025-07-31 14:49

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0014_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='bank_additions',
        ),
        migrations.RemoveField(
            model_name='report',
            name='beginning_cash_on_bank',
        ),
        migrations.RemoveField(
            model_name='report',
            name='beginning_cash_on_hand',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ending_cash_on_bank',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ending_cash_on_hand',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hand_additions',
        ),
        migrations.AddField(
            model_name='report',
            name='auditor',
            field=myapp1.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='chairman',
            field=myapp1.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='treasurer',
            field=myapp1.fields.ShortCharField(blank=True, default='', max_length=50),
        ),
    ]
