# Generated by Django 5.2.4 on 2025-08-01 03:43

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0015_remove_report_bank_additions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=myapp1.fields.ChoiceIntegerField([(0, 'Electric Bill'), (1, 'Water Bill'), (2, "Priest's Stipend"), (3, 'Food'), (4, 'Transportation'), (5, 'Repairs/Maintenance'), (6, 'Allowance for Care Taker'), (7, 'Worship'), (8, 'Evangelization'), (9, 'Service'), (10, 'Stewardship'), (11, 'Youth'), (12, 'Family & Life'), (13, 'Recollection/Seminar'), (14, 'Others'), (15, 'Payable to')], 0),
        ),
    ]
